### ISSUE TITLE
Error Loading Chart: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by mjjor** [ankane/chartkick#219]
I am having an issue in rails 4 getting a timeline chart to display.

This error is thrown when i run the page:
Error Loading Chart: Cannot read property 'replace' of undefined

Controller:
@events = Events.select(:id, :event_types, :starttime, :endtime).where(project_masters_id: params[:proj_id], phase_masters_id: params[:id])

View:
<%= timeline( @events.each do |evnt| [evnt]) %>

I have also tried
<%= timeline( @events.map {|evnt| [evnt]} end ) %>
with the same results.

Any help would be appreciated.

**Comment by afinebojangle** [comment]
I have the same error, but with different code:

In my view I have a form at the top which makes an ajax call that should return data to place in the same view:

```
<div class="container">
    <div class="row">
        <%= simple_form_for @capm_regression, url: {action: "capm_graph"}, html: {method: "get"}, remote: true do |f| %>
            <%= f.input :ticker %>
            <%= f.input :index %>
            <%= f.input :start_date, as: :string, input_html: {type: :date}, label: 'Start Date' %>
            <%= f.input :end_date, as: :string, input_html: {type: :date}, label: 'End Date' %>
            <%= f.button :submit, class: "btn-primary" %>
        <% end %>
        <hr>
    </div>
    
    <div class="graph_box">
        <h4>This is where the graph goes!</h4>
    </div>
</div>
```

The controller action this form submits to:

```
def capm_graph
    @capm_regression = Capm_regression.new(capm_regression_params)
    
    @capm_graph = @capm_regression.capm_regress
    
    respond_with(@capm_graph) do |format|
      format.html {redirect_to capm_index_path}
    end

  end
```

The js file that hides the div box that is rendered before the form is submitted and adds the graph after the controller has processed:
```
$("div.graph_box").replaceWith("<%= escape_javascript(render(partial: 'capm_graph')) %>");
```

and lastly the partial that should be the graph:
```
<div class="graph_box">
    <%= line_chart @capm_graph %>
</div>
```

I get the following html instead of a line graph:

```
<div id="chart-1" style="height: 300px; text-align: center; color: rgb(255, 0, 0); line-height: 300px; font-size: 14px; font-family: 'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif;">Error Loading Chart: Cannot read property 'replace' of undefined</div>
```

Thanks for reading!

**Comment by mlohstroh** [comment]
I just spent a good time debugging this, and I finally figured out why it kept throwing that same error at me.

I was submitting data like this, and it kept giving me that error.

```ruby
<%= line_chart [
  {name: 'series1', data: { timestamp: 'entry', timestamp: 'entry' } },
  {name: 'series2', data: { timestamp: 'entry', timestamp: 'entry' } }
] %>
````

The documentation says that you can submit data as a hash or an array like so.
```ruby
<%= pie_chart({"Football" => 10, "Basketball" => 5}) %>
<%= pie_chart [["Football", 10], ["Basketball", 5]] %>
```
However, you cannot submit multiple data sources as hashes. You must submit them as arrays of arrays. So I changed my data set to look more like this, and it worked.

```ruby
<%= line_chart [
  {name: 'series1', data: [ [timestamp, 'entry'], [timestamp: 'entry'] ] },
  {name: 'series2', data: [ [timestamp, 'entry'], [timestamp: 'entry'] ] }
] %>
````

This is a weird quirk, and I'm not sure if it's intentional or not. 

Are you aware of this @ankane?

**Comment by ankane** [comment]
Multiple series can be submitted as hashes - the multiple series example on chartkick.com does this. It sounds like this error is happening when the data format is incorrect, so going to close. Happy to accept a PR for a friendlier error message when the format is off (unsure how difficult that will be).
