### ISSUE TITLE
Add Information on Chart for value min and max

### ISSUE THREAD

**Issue by zaychoer** [ankane/chartkick#487]
I like this gem so much. Thanks ankane.
I wan to ask about add information inside chart.
Can we add information inside chart when there is value min and max
Like this
<img width="602" alt="Screen Shot 2019-05-29 at 14 53 52" src="https://user-images.githubusercontent.com/30226925/58539983-ab8aa580-8222-11e9-8e24-28680dd42df0.png">
Thanks.

**Comment by ankane** [comment]
Hey @zaychoer, Chartkick doesn't provide a special way to do this, so you'll need to see if it's possible with the `library` option. Otherwise, you'll need to use the charting library directly. Unfortunately, I don't have the bandwidth to help with specific customizations, so try posting on Stack Overflow if you need additional help.
