### ISSUE TITLE
Passing in custom options

### ISSUE THREAD

**Issue by michiels** [ankane/chartkick#5]
Wow! Thank you for this gem. It's so nice and simple.

I browsed through the JS and Ruby helpers and I was wondering if it would be possible to pass in options via the Ruby helper which get passed into the Highcharts or Google Charts JS options. I tried something like:

``` ruby
<%= line_chart series, legend: { position: "left" } %>
```

Is this something that would work?

**Comment by genlighten** [comment]
I'm trying to pass the lineTension: 0 option to charts.js so I can get straight lines between points instead of Bezier curves. I've tried
`line_chart series, library: { lineTension: 0 }`
  and
`line_chart series, library: { options: { lineTension: 0 }}`
with no effect.

Any suggestions for the right syntax in this situation?

Thanks!

--Dean

**Comment by aishmita-aggarwal** [comment]
I am facing a similar problem as @genlighten. Did we find any results?

**Comment by walreyes** [comment]
Someone found a solution to your problem @genlighten?

**Comment by deztrucktor** [comment]
@genlighten I had the same problem, but the following workaround seems to work:
Chart.defaults.global.elements.line.tension = 0.001;

Setting it to 0 doesn't work, but 0.001 does.

**Comment by ndbroadbent** [comment]
If anyone sees this, I figured out how to get straight lines with Chart.js 2.7.0 and chartkick 2.3.5:

```ruby
line_chart data, library: { elements: { line: { tension: 0 }}}
```

(Reference: https://github.com/chartjs/Chart.js/issues/2170#issuecomment-200850282)
