### ISSUE TITLE
TypeError: type is not a constructor

### ISSUE THREAD

**Issue by alex-hedrevich** [ankane/chartkick#543]
All of the sudden Google Maps stopped working with error:

```
chartkick.esm.js:1440 Uncaught (in promise) TypeError: type is not a constructor
    at defaultExport.drawChart (chartkick.esm.js:1440)
    at Object.callback (chartkick.esm.js:1362)
    at defaultExport.runCallbacks (chartkick.esm.js:1498)
    at callback (chartkick.esm.js:1467)
    at loader.js:142
    at loader.js:57
```

**To reproduce**
https://chartkick.com/react look at Geo Chart section. Shows loading...

**Comment by ankane** [comment]
Hey @alex-hedrevich, thanks for reporting! It looks like there was a new release today and the GeoChart was possibly moved to a new Google Charts package.

Fix in Chartkick.js: https://github.com/ankane/chartkick.js/commit/4721d62f2a5417418fd25903a83647549b31a18e

I've also updated the vendored copy of Chartkick.js in the Ruby gem so it's available on master.

I'll make a new release once Google confirms the change was intentional, since it's not included in the changelog: https://github.com/google/google-visualization-issues/issues/2845

**Comment by ankane** [comment]
New version is out. Thanks again @alex-hedrevich!

**Comment by alex-hedrevich** [comment]
Thank you @ankane for such a quick fix!!!
