### ISSUE TITLE
Using javascript functions when passing options to library

### ISSUE THREAD

**Issue by kakoni** [ankane/chartkick#60]
Trying to do some advanced x-axis label formatting with with highcharts;

``` ruby
<%= column_chart weekly_samples_charts_path, library: {
  xAxis: {
    labels: {
      enabled: true,
      formatter: function() { ... }
    }
  }
} %>
```

but this failes, I get `undefined method `function' for #<#<Class:0x007f8dd57e3258>:0x007f8dd53cb8c8>` error. 

Is this expected?

**Comment by sebastianiorga** [comment]
Hacked something to make this work. No idea if it's the proper solution, but I'll leave it here in case anyone is just looking for a way to Make It Work.

My actual implementation involves some classes wrapping chartkick and jquery datatables, but I've stripped it down to the bare bones for this example. Modify as needed for your purposes.

In some javascript file available in your view
`window.exampleFunction = function () { return 'function_name example' }`
In your view
`<%= chartkick_render_chart_hack %>`

In ApplicationHelper
```ruby
FUNCTION_NAME_DELIMITER = 'FNNAME'
FUNCTION_START = 'FNSTART'
FUNCTION_END = 'FNEND'

# Assuming you are using the Highcharts adapter
def chartkick_render_chart_hack(chart_type = :column_chart, options = nil)
  # Or generate the options elsewhere and pass them in. Just make sure to use the helpers.
  options ||= { 
    library: { 
      xAxis: { labels: { formatter: js_inline('function () { return "inline_example"; }') } },
      yAxis: { labels: { formatter: js_function_name('exampleFunction') } }
    }   
  }

  # chart_type might end up being :column_chart, :bar_chart, etc 
  # whatever chart method symbol from chartkick you want to use
  rendered = send chart_type, data, options

  # Strip out the delimiters from the generated html/js/json. 
  # The effect is it turns the JSON options into a plain javascript object. 
  # The function bodies/names are no longer strings. Magic.
  rendered
    .gsub(/"#{ChartTemplate::FUNCTION_NAME_DELIMITER}([^""]*)"/, '\1')
    .gsub(/"#{FUNCTION_START}(.*)#{FUNCTION_END}"/, '\1')
    .gsub('\"', '"')
end

# Example: onClick: js_function_name('someFunction').
# someFunction needs to be available as window.highchartsExtras.someFunction.
def js_function_name(fn)
  "#{FUNCTION_NAME_DELIMITER}highchartsExtras.#{fn}"
end

# Example: onClick: js_inline('function () { alert("wooo"); }')
def js_inline(js)
  "#{FUNCTION_START}#{js}#{FUNCTION_END}"
end
```

Of course, you need to make sure that you are using the helper functions to annotate your embedded  'js' code. You also need to make sure to always wrap the call to the actual chartkick method with the helper. So if you are rendering the chart in a controller in response to an AJAX call, it needs to use the helper method etc.

Haven't run this code, since it's extracted from a more complicated wrapper I'm building around chartkick, but it should work.

Disclaimer: this may be a mad way of implementing this, but it seems to work fine for my purposes.

Disclaimer 2: this can be implemented straight into the various chartkick methods: make js_inline and js_function_name(or equivalent) available in the view or as static methods, then have methods like column_chart innately try to parse out their output before they return it. However, I haven't actually looked into the chartkick internals to see what it would take.

**Comment by satheeshcsedct** [comment]
Is there any progress on this, I am looking for the proper fix to pass the js function to formatter.

**Comment by austinarchibald** [comment]
@satheeshcsedct, yes I am wondering the same thing. All I want to do is add a measly '%' to the xAxis values. Why does it have to be so difficult? Is there a working workaround? I tried something like this, but I can't get it to work.

```js
$(".highcharts-container").on("chartkick:before", function (e){
    yAxis: {
      labels: {
        formatter: function () {
          return this.value+'%';
        }
      }
    }
  });
```

**Comment by itkin** [comment]
+1

**Comment by ankane** [comment]
Just fyi, the preferred way to do this is to use the `setOptions` method in the JavaScript API. https://github.com/ankane/chartkick#javascript-api

**Comment by ConfusedVorlon** [comment]
just to add an example here

where I'm adding hs.tens_label_callback - and I don't want to clobber the options that are set through standard options like 'stacked' or through the library option.

```
<%= column_chart test_team_dashboard_path, download: "test", stacked: true, id: "test-chart",
library: {
	animation: {
		easing: 'easeOutQuad',"duration": 200
		}
	}
%>
<script>

	var chart = Chartkick.charts["test-chart"];
	var newOptions = {
		library: {
			scales:{
				yAxes: [{
					ticks: {
						beginAtZero:true,
						suggestedMax: 20,
						callback: hs.tens_label_callback
					}
				}]
			}
		}
	}
	var mergedOptions = jQuery.extend(chart.options,newOptions)
	chart.setOptions(mergedOptions);

</script>
```

**Comment by CyberDeck** [comment]
In line with the comment from @sebastianiorga, I developed the following solution:

```ruby
require 'active_support/core_ext/module/aliasing'

module ChartkickMixinJavascriptFunctions
  FUNCTION_NAME_DELIMITER = 'FNNAME'
  FUNCTION_START = 'FNSTART'
  FUNCTION_END = 'FNEND'

  module Helper
    def js_function_name(fn)
      "#{ChartkickMixinJavascriptFunctions::FUNCTION_NAME_DELIMITER}#{fn}"
    end

    def js_inline(js)
      "#{ChartkickMixinJavascriptFunctions::FUNCTION_START}#{js}#{ChartkickMixinJavascriptFunctions::FUNCTION_END}"
    end
  
    private
    def chartkick_chart(klass, data_source, options)
      rendered = super(klass, data_source, options)
  
      rendered
        .gsub(/"#{ChartkickMixinJavascriptFunctions::FUNCTION_NAME_DELIMITER}([^""]*)"/, '\1')
        .gsub(/"#{ChartkickMixinJavascriptFunctions::FUNCTION_START}(.*)#{ChartkickMixinJavascriptFunctions::FUNCTION_END}"/, '\1')
        .gsub('\"', '"')
        .html_safe
    end 

  end
end
  
Chartkick::Helper.send(:prepend, ChartkickMixinJavascriptFunctions::Helper)
```

Just put the code into the Chartkick initializer file, e.g. `config/initializers/chartkick.rb`.

Afterwards, you can call e.g. `line_chart` the usual way and wrap options strings into the `js_inline` etc. helpers.
